In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from build_utils import get_universalization_summary, get_outcome_metrics
from source_comparison_utils import (
    regression_by_source, 
    add_effect_sizes_by_source, 
    add_zscores_by_source,
    plot_regression_by_source, 
    plot_effect_vs_sd_by_source,
    plot_zscores_by_source
)

In [5]:
# Retrieve summary statistics across maps and sources
run_type="level-x"
df = get_universalization_summary(run_type=run_type,recompute=True) # set to True to rebuild analysis files from raw simulation data
df

Built 39 scenario outcome rows and saved to ../data/scenarios/outcome_metrics.csv

,scenario_label,xp_name,map_name,condition,aggregate_welfare,inequality,cardinal_harm,ordinal_harm_blind,gini
0,new_yes_10mod,new_yes_10mod,10esque,1cut,-0.000000,0.000000,0.415584,4.0,0.000000
1,new_yes_7esque,new_yes_7esque,7esque,1cut,-0.000000,0.000000,0.177778,2.0,0.000000
2,new_yes_9esque,new_yes_9esque,9esque,1cut,0.437500,0.020833,0.208333,5.0,0.012443
3,maybe_4,maybe_4,maybe_4,1cut,0.604651,-0.093023,0.000000,5.0,-0.000209
4,maybe_5,maybe_5,maybe_5,1cut,0.603448,-0.103448,0.000000,4.0,-0.007378
5,maybe_6,maybe_6,maybe_6,1cut,0.392157,-0.078431,0.000000,3.0,-0.016892
6,new_maybe_1,new_maybe_1,new_maybe_1,1cut,0.674419,-0.069767,0.000000,7.0,0.012931
7,new_maybe_2,new_maybe_2,new_maybe_2,1cut,0.340909,-0.090909,0.000000,2.0,-0.023333
8,new_maybe_3,new_maybe_3,new_maybe_3,1cut,0.508475,-0.135593,0.033898,4.0,-0.022018
9,new_maybe_4,new_maybe_4,new_maybe_4,1cut,0.357143,-0.125000,0.089286,3.0,-0.020570
10,new_maybe_5,new_maybe_5,new_maybe_5,1cut,0.424528,-0.047170,0.235849,7.0,-0.004658
11,new_maybe_6,new_maybe_6,new_maybe_6,1cut,0.375000,0.020833,0.000000,2.0,0.003922
12,new_no_1,new_no_1,no_line_1,1cut,0.466667,-0.088889,0.000000,4.0,-0.015720
13,new_no_2,new_no_2,no_line_2,1cut,0.738095,-0.023810,0.000000,6.0,0.025583
14,new_no_3,new_no_3,no_line_3,1cut,0.441860,-0.093023,0.000000,3.0,-0.019650
15,noline_a,noline_a,no_line_A,1cut,0.571429,-0.095238,0.000000,4.0,-0.007500
16,noline_b,noline_b,no_line_B,1cut,0.630435,-0.065217,0.000000,6.0,0.009396
17,noline_c,noline_c,no_line_C,1cut,0.660000,0.020000,0.000000,6.0,0.022304
18,noline_d,noline_d,no_line_D,1cut,0.486486,-0.108108,0.000000,3.0,-0.021936
19,new_yes_10,new_yes_10,yes_line_10,1cut,-0.298701,-0.090909,0.805195,6.0,-0.026635
20,new_yes_7,new_yes_7,yes_line_7,1cut,-0.000000,0.000000,0.355556,4.0,0.000000
21,new_yes_8,new_yes_8,yes_line_8,1cut,-0.068966,-0.068966,0.344828,3.0,-0.024241
22,new_yes_9,new_yes_9,yes_line_9,1cut,0.258065,0.000000,0.290323,7.0,0.006299
23,yesline_b,yesline_b,yes_line_B,1cut,0.390625,-0.062500,0.000000,6.0,-0.007333
24,yes_line_c,yes_line_c,yes_line_C,1cut,0.733333,0.022222,0.000000,7.0,0.030064
25,yes_line_d,yes_line_d,yes_line_D,1cut,0.568182,-0.090909,0.000000,6.0,-0.004651
26,yes_line_e,yes_line_e,yes_line_E,1cut,-1.838710,-0.112903,1.838710,0.0,-0.051644
27,yes_line_f,yes_line_f,yes_line_F,1cut,0.470588,0.156863,0.000000,7.0,0.021526
28,new_maybe_3_bad,new_maybe_3_bad,new_maybe_3,1cut_bad,0.406780,-0.186441,0.101695,4.0,-0.038487
29,new_maybe_4_bad,new_maybe_4_bad,new_maybe_4,1cut_bad,-0.214286,-0.250000,0.535714,5.0,-0.071839
30,new_maybe_5_bad,new_maybe_5_bad,new_maybe_5,1cut_bad,-0.179245,-0.047170,0.660377,6.0,-0.029518
31,new_yes_10_bad,new_yes_10_bad,yes_line_10,1cut_bad,-1.714286,-0.064935,1.974026,5.0,-0.064954
32,yesline_b_bad,yesline_b_bad,yes_line_B,1cut_bad,0.125000,-0.140625,0.125000,1.0,-0.032296
33,yes_line_c_bad,yes_line_c_bad,yes_line_C,1cut_bad,0.600000,-0.088889,0.022222,4.0,0.002025
34,yes_line_d_bad,yes_line_d_bad,yes_line_D,1cut_bad,0.045455,-0.068182,0.454545,6.0,-0.017437
35,new_maybe_3_badder,new_maybe_3_badder,new_maybe_3,1cut_badder,-0.881356,-0.135593,1.203390,5.0,-0.056956
36,yesline_b_badder,yesline_b_badder,yes_line_B,1cut_badder,-0.343750,-0.062500,0.343750,0.0,-0.017915
37,yes_line_c_badder,yes_line_c_badder,yes_line_C,1cut_badder,-0.311111,-0.111111,0.488889,3.0,-0.054851
38,yes_line_d_badder,yes_line_d_badder,yes_line_D,1cut_badder,-0.204545,-0.136364,0.704545,7.0,-0.034940

In [3]:
comp=pd.read_csv("../data/scenarios/completion_times.csv")
l=pd.read_csv("../data/scenarios/scenario_lookup.csv")
agent_cols = [c for c in comp.columns if c.startswith("agent_")]

m="new_maybe_6"
cond="1cut"

line = comp[(comp["map"] == m) & (comp["condition"] == "line")][agent_cols].iloc[0].to_numpy()
world = comp[(comp["map"] == m) & (comp["condition"] == cond)][agent_cols].iloc[0].to_numpy()

compute_metrics(world,line)

{'aggregate_welfare': np.float64(0.375),
 'ordinal_harm_blind': np.float64(2.0),
 'cardinal_harm': np.float64(0.0),
 'inequality': np.float64(0.020833333333333332),
 'gini': np.float64(0.003921771523178963)}

In [12]:
build_processed_sim_all_maps("kwon2023")

Processed 29 maps for run_type='kwon2023' and saved to ../data/simulations/kwon2023/processed

In [13]:
df=build_outcome_metrics()
df[ df["map_name"]==m]

Built 39 scenario outcome rows and saved to ../data/scenarios/outcome_metrics.csv

,scenario_label,xp_name,map_name,condition,aggregate_welfare,inequality,cardinal_harm,ordinal_harm_blind,gini
11,new_maybe_6,new_maybe_6,new_maybe_6,1cut,0.375,0.020833,0.0,2.0,0.003922

In [211]:
line = df [ (df["map"] == map_name) & (df["condition"] == "line") ] 
cut = df [ (df["map"] == map_name) & (df["condition"] == cut_condition) ]

line_times=line.iloc[0][agent_cols]
cut_times = cut.iloc[0][agent_cols]

agg_w = - ( cut_times.sum() - line_times.sum() ) / line_times.max()
agg_w

np.float64(0.25806451612903225)

In [212]:
compute_metrics(
    cut_times,
    line_times)

{'aggregate_welfare': np.float64(0.25806451612903225),
 'ordinal_harm': np.float64(7.0),
 'cardinal_harm': np.float64(0.2903225806451613),
 'inequality': np.float64(0.0),
 'gini': np.float64(0.006299407114624511)}

In [209]:
line = df [ (df["map"] == map_name) & (df["condition"] == "line") ] 
cut = df [ (df["map"] == map_name) & (df["condition"] == cut_condition) ]

line_times=line.iloc[0][agent_cols]
cut_times = cut.iloc[0][agent_cols]

line_rank = line_times.rank(method="first")   # should be 1..8 in line, but this is robust
cut_rank = cut_times.rank(method="first")   # should be 1..8 in line, but this is robust
cut_rank

agent_1    1.0
agent_2    2.0
agent_3    4.0
agent_4    5.0
agent_5    6.0
agent_6    7.0
agent_7    3.0
agent_8    8.0
Name: 7, dtype: float64

In [74]:
line_times.sum()

np.int64(392)

In [53]:
agent_cols = [c for c in df.columns if c.startswith("agent_")]

In [36]:
def aggregate_welfare( df, map_name, cut_condition):

    line = df [ df["map"] == map_name & df ["condition"] == "line"]

    
    
    agent_cols = [c for c in df.columns if c.startswith("agent_")]
    
    total_line =

SyntaxError: EOL while scanning string literal (936817315.py, line 3)

In [32]:
badder = sc [ sc["condition"] == "1cut_badder"] 
bad = sc [ sc["condition"] == "1cut_bad"] 
cut = sc [ sc["condition"] == "1cut"] 
len(cut)+len(bad)+len(badder)

40

In [11]:
xp=pd.read_csv("../data/experimental/cross_cultural_pilot_summary.csv")
xp=xp.sort_values("map")
xp

,country,iso2,iso3,map,rating_mean,rating_stderr,sample_size
308,Ukraine,UA,UKR,maybe_4,2.857143,0.704698,7
260,United States,US,USA,maybe_4,3.272727,0.487869,11
29,Canada,CA,CAN,maybe_4,4.000000,0.471405,10
111,Israel,IL,ISR,maybe_4,3.800000,0.427618,15
281,Spain,ES,ESP,maybe_4,4.071429,0.266526,14
...,...,...,...,...,...,...,...
53,Israel,IL,ISR,yesline_f,3.333333,0.440959,9
40,India,IN,IND,yesline_f,3.400000,0.812404,5
249,United States,US,USA,yesline_f,4.000000,0.389249,12
250,Ukraine,UA,UKR,yesline_f,4.555556,0.231819,18
273,United Kingdom,GB,GBR,yesline_f,3.555556,0.647884,9

In [23]:
xp.groupby("map").count()

,country,iso2,iso3,rating_mean,rating_stderr,sample_size
map,,,,,,
maybe_4,8,8,8,8,8,8
maybe_5,8,8,8,8,8,8
maybe_6,8,8,8,8,8,8
new_maybe_1,8,8,8,8,8,8
new_maybe_2,8,8,8,8,8,8
new_maybe_3,8,8,8,8,8,8
new_maybe_3_bad,8,8,8,8,8,8
new_maybe_3_badder,8,8,8,8,8,8
new_maybe_4,8,8,8,8,8,8
new_maybe_4_bad,8,8,8,8,8,8
new_maybe_5,8,8,8,8,8,8
new_maybe_5_bad,8,8,8,8,8,8
new_maybe_6,8,8,8,8,8,8
new_no_1,8,8,8,8,8,8
new_no_2,8,8,8,8,8,8
new_no_3,8,8,8,8,8,8
new_yes_10,8,8,8,8,8,8
new_yes_10_bad,8,8,8,8,8,8
new_yes_10mod,8,8,8,8,8,8
new_yes_7,8,8,8,8,8,8
new_yes_7esque,8,8,8,8,8,8
new_yes_8,8,8,8,8,8,8
new_yes_9,8,8,8,8,8,8
new_yes_9esque,8,8,8,8,8,8
noline_a,8,8,8,8,8,8
noline_b,8,8,8,8,8,8
noline_c,8,8,8,8,8,8
noline_d,8,8,8,8,8,8
yesline_b,8,8,8,8,8,8
yesline_b_bad,8,8,8,8,8,8
yesline_b_badder,8,8,8,8,8,8
yesline_c,8,8,8,8,8,8
yesline_c_bad,8,8,8,8,8,8
yesline_c_badder,8,8,8,8,8,8
yesline_d,8,8,8,8,8,8
yesline_d_bad,8,8,8,8,8,8
yesline_d_badder,8,8,8,8,8,8
yesline_e,8,8,8,8,8,8
yesline_f,8,8,8,8,8,8

In [24]:
xp['map'].nunique()

39

In [33]:
all_problems = ["no_line_1_test.pddl", "no_line_2_test.pddl", "no_line_3_test.pddl", "yes_line_7_test.pddl", "yes_line_8_test.pddl", "yes_line_9_test.pddl", "yes_line_10_test.pddl", "7esque_test.pddl", "9esque_test.pddl", "10esque_test.pddl", "maybe_4.pddl", "maybe_5.pddl", "maybe_6.pddl", "new_maybe_1.pddl", "new_maybe_2.pddl", "new_maybe_3.pddl", "new_maybe_4.pddl", "new_maybe_5.pddl", "new_maybe_6.pddl", "no_line_A.pddl", "no_line_B.pddl", "no_line_C.pddl", "no_line_D.pddl", "yes_line_A.pddl", "yes_line_B.pddl", "yes_line_C.pddl", "yes_line_D.pddl", "yes_line_E.pddl", "yes_line_F.pddl"]
len(all_problems)

29

In [237]:
build_processed_sim_one_map("kwon2023", "new_maybe_5")

[ 34.  31.  57.  54.  81.  78. 106. 103.]
[ 30. 126.  55.  98.  73. 150. 178. 205.]
[ 30. 102.  54. 179.  76. 155. 397. 130.]
[ 32.  75.  50. 296. 126. 101. 168. 261.]
[ 30.  56.  94. 213. 190. 116. 137. 161.]
[ 37.  58.  81. 168. 106. 144. 196. 218.]

'Result for new_maybe_5 in kwon2023 run saved to ../data/simulations/kwon2023/processed/new_maybe_5.csv'

In [229]:
def compute_metrics( world, line ):
    """
    Compute metrics by comparing completion times in world to those in the line baseline.

    line: size 8 array with completion times when agents follow a line.
    world: size 8 array with completion times in an alternate world.

    Returns a dict with outcome measures when world is a scenario where 1 agent cuts the line (1cut, 1cut_bad, 1cut_badder),
    and a univerlizability estimates when world is a simulation run.
    """
    # Make sure we have pandas Series so .clip and .rank work
    line = pd.Series(line, dtype=float)
    world = pd.Series(world, dtype=float)
    
    line_last = line.max() # Completion time for last agent in line; used to normalize metrics
    
    # Aggregate welfare (positive: total completion times are lower than in line; ie welfare is improved)
    aggregate_welfare = - ( world.sum() - line.sum() ) / line_last
    
    # Inequality (positive: increase in gap btw first and last)
    gap_world = world.max() - world.min()
    gap_line = line_last - line.min()
    inequality = ( gap_world - gap_line ) / line_last

    # Cardinal harm (always positive; normalized sum of increases in completion time)
    positive_differences = (world - line).clip(lower=0)
    cardinal_harm =  positive_differences.sum() / line_last

    
    # Ordinal harm (always positive; sum of increases in rank)
    ### NOTE: this is a "blind" version. 
    ### With just completion times, I can't tell if a line-cutter is using a different source or not. Kwon2023 reports a non-blind version, probably done by hand
    world_rank = world.rank(method="first")
    line_rank = line.rank(method="first")
    positive_rank_differences = (world_rank - line_rank).clip(lower=0)
    ordinal_harm = positive_rank_differences.sum()

    # Gini (difference in Gini coefficients)
    gini = compute_gini(world) - compute_gini(line)
    
    return {
        "aggregate_welfare": aggregate_welfare,
        "ordinal_harm": ordinal_harm,
        "cardinal_harm": cardinal_harm,
        "inequality": inequality,
        "gini": gini
    }

In [181]:

def compute_gini(values):
    """
    Compute Gini coefficient for a 1D array of non-negative values.
    """
    x = np.asarray(values, dtype=float)
    if np.all(x == 0):
        return np.nan
    
    x_sorted = np.sort(x)
    n = len(x_sorted)
    # 2 * sum(i * x_i) / (n * sum(x_i)) - (n + 1)/n
    g = (2.0 * np.sum(np.arange(1, n + 1) * x_sorted)) / (n * np.sum(x_sorted)) - (n + 1) / n
    return g

In [182]:
display(cut_times-line_times).clip(lower=0)

agent_1      0
agent_2      0
agent_3      0
agent_4      0
agent_5      0
agent_6      0
agent_7    -17
agent_8     -4
dtype: object

AttributeError: 'NoneType' object has no attribute 'clip'

In [170]:
display(cut_times)
display(line_times)

agent_1    40
agent_2    42
agent_3    49
agent_4    51
agent_5    57
agent_6    59
agent_7    60
agent_8    64
Name: 56, dtype: object

agent_1    36
agent_2    40
agent_3    44
agent_4    48
agent_5    52
agent_6    56
agent_7    60
agent_8    64
Name: 53, dtype: object

In [171]:
compute_metrics(
    cut_times, line_times)

24
28
-0.0625

{'aggregate_welfare': np.float64(-0.34375),
 'ordinal_harm': <NA>,
 'cardinal_harm': np.float64(0.34375),
 'inequality': np.float64(-0.0625),
 'gini': np.float64(-0.01791469194312789)}